-- Direct Invoice smoke test.
--
-- Run this in the Supabase SQL Editor AFTER `supabase db push` has applied
-- supabase/migrations/20261004000000_direct_invoices.sql.
--
-- WHY EVERY DOCUMENT USES A FUTURE DATE (read this before "fixing" it)
--
-- Invoice and Delivery Challan numbers come from SEQUENCES, and PostgreSQL
-- sequences are deliberately NOT transactional: `rollback` restores rows but
-- does NOT give back a value already handed out by nextval(). Both numbers are
-- generated by a BEFORE INSERT trigger --
--   invoices.invoice_number           <- invoices_assign_number()
--   receiving_documents.document_number <- receiving_documents_assign_number()
-- -- so every row this test inserts into those two tables would silently
-- consume a real business-document number, permanently, even though the whole
-- test ends in a ROLLBACK. Measured on a scratch database, the pre-fix version
-- of this file burned 3 values of inv_seq_AK_2026 AND 1 value of
-- dc_seq_AK_2026 -- i.e. the first real invoice would have been
-- INV/2026-27/004 and the first real challan AK/2026-27/039, both leaving a
-- gap in a legal, consecutive document series.
--
-- So this test pins BOTH the invoice date and the fixture challan's
-- transaction_date to date '2099-04-01'. The generators derive the financial
-- year from that date, so they resolve to inv_seq_AK_2099 / dc_seq_AK_2099 --
-- sequences the app has never used and which are created on demand INSIDE this
-- transaction. That DDL is transactional, so the ROLLBACK drops them again.
--
-- Net effect: this test leaves ZERO residue -- no rows, no sequence advance,
-- no leftover sequences -- and it is safe to run on production. Reverting the
-- dates to current_date is what makes it unsafe.
--
-- HOW THE AUTH GUARD IS SATISFIED
-- create_invoice / update_invoice are SECURITY DEFINER but still check
-- public.current_role(), which reads the JWT via auth.uid(). In the SQL editor
-- there is no session, so the tests temporarily point the request JWT claim at
-- an existing active admin. That is a local, transaction-scoped
-- `set_config(..., true)` override — it is reverted by the ROLLBACK and never
-- touches a real session.
--
-- Every check raises an exception on failure, so a non-zero error means the
-- named invariant broke.

begin;

-- ---------------------------------------------------------------------------
-- Test fixture
-- ---------------------------------------------------------------------------
do $$
declare
  v_admin uuid;
begin
  select id into v_admin
  from public.profiles
  where role = 'admin' and is_active
  limit 1;

  if v_admin is null then
    raise exception 'SETUP: no active admin profile found. Cannot satisfy the RPC role guard.';
  end if;

  -- Make auth.uid() / current_role() resolve to a real admin for this txn.
  perform set_config(
    'request.jwt.claims',
    json_build_object('sub', v_admin::text)::text,
    true
  );
end $$;

-- A party for both invoices, plus a component and a Send challan to bill.
do $$
declare
  v_party uuid;
  v_comp uuid;
  v_doc uuid;
  v_item uuid;
begin
  insert into public.companies (name, location)
  values ('ZZ Smoke Test Party', 'Smoke City')
  returning id into v_party;

  insert into public.materials (name, unit, is_active)
  values ('ZZ Smoke Test Component', 'pieces', true)
  returning id into v_comp;

  -- A billable challan is a Send: type='given', going OUT to a customer.
  -- transaction_date is pinned to the far future so the DC-number trigger burns
  -- dc_seq_AK_2099 instead of the live dc_seq_AK_2026 (see the header note).
  insert into public.receiving_documents (
    company_id, type, kind, source, status, document_number, transaction_date
  )
  values (v_party, 'given', 'other', 'customer', 'completed',
          'ZZ-SMOKE-CHALLAN', date '2099-04-01')
  returning id into v_doc;

  insert into public.receiving_document_items (
    document_id, line_no, line_type, component_id, item_name,
    quantity, unit, unit_price, gst_percent
  )
  values (v_doc, 1, 'component', v_comp, 'ZZ Smoke Test Item',
          2, 'pieces', 100.00, 18.00)
  returning id into v_item;

  perform set_config('smoke.party',    v_party::text, true);
  perform set_config('smoke.component', v_comp::text,  true);
  perform set_config('smoke.challan',  v_doc::text,   true);
  perform set_config('smoke.item',     v_item::text,  true);
end $$;

-- ---------------------------------------------------------------------------
-- 1. DIRECT INVOICE — create with an empty challan array
-- ---------------------------------------------------------------------------
do $$
declare
  v_number text;
  v_inv uuid;
  v_lines bigint;
  v_links bigint;
  v_sub numeric;
  v_cgst numeric;
  v_sgst numeric;
  v_gst numeric;
  v_total numeric;
  v_src_nulls bigint;
begin
  v_number := public.create_invoice(
    p_company_id  := current_setting('smoke.party')::uuid,
    p_invoice_date := date '2099-04-01',
    p_our    := jsonb_build_object('company_name', 'Smoke AKPC'),
    p_party  := jsonb_build_object('name', 'ZZ Smoke Test Party', 'state', 'Maharashtra'),
    -- EMPTY, not null: both must read as "direct", but [] is what the client
    -- actually sends (see createInvoiceApi).
    p_challans := '{}'::uuid[],
    p_lines := jsonb_build_array(
      jsonb_build_object(
        'line_no', 1,
        -- manual line: BOTH source columns must be null
        'source_document_id', null,
        'source_item_id', null,
        'line_type', 'other',
        'component_id', null,
        'item_name', 'Manual Widget',
        'quantity', 3,
        'unit', 'pieces',
        'hsn_code', '8481',
        'item_remarks', 'typed by hand',
        'unit_price', 250.00,
        'gst_percent', 18
      ),
      jsonb_build_object(
        'line_no', 2,
        'source_document_id', null,
        'source_item_id', null,
        'line_type', 'other',
        'component_id', null,
        'item_name', 'Manual Bolt',
        'quantity', 10,
        'unit', 'pieces',
        'hsn_code', null,
        'item_remarks', null,
        'unit_price', 12.50,
        'gst_percent', 12
      )
    )
  );

  select id into v_inv from public.invoices where invoice_number = v_number;

  if v_inv is null then
    raise exception 'FAIL 1a: create_invoice returned a number but no row exists.';
  end if;

  -- Mode + link count
  if (select invoice_type from public.invoices where id = v_inv) <> 'direct' then
    raise exception 'FAIL 1b: invoice_type is not ''direct''.';
  end if;

  select count(*) into v_links
  from public.invoice_challans where invoice_id = v_inv;
  if v_links <> 0 then
    raise exception 'FAIL 1c: a direct invoice has % invoice_challans row(s), expected 0.', v_links;
  end if;

  -- Items landed with a null source
  select count(*) into v_lines from public.invoice_items where invoice_id = v_inv;
  if v_lines <> 2 then
    raise exception 'FAIL 1d: expected 2 invoice_items, got %.', v_lines;
  end if;

  select count(*) into v_src_nulls
  from public.invoice_items
  where invoice_id = v_inv and source_document_id is null;
  if v_src_nulls <> 2 then
    raise exception 'FAIL 1e: expected both direct items to have a NULL source_document_id, got % null of %.',
      v_src_nulls, v_lines;
  end if;

  -- Money: 3 x 250 = 750 (+135 GST) ; 10 x 12.50 = 125 (+15 GST)
  -- subtotal 875.00, gst 150.00, total 1025.00, cgst 75.00, sgst 75.00
  select subtotal, cgst_total, sgst_total, gst_total, total_amount
  into v_sub, v_cgst, v_sgst, v_gst, v_total
  from public.invoices where id = v_inv;

  if v_sub <> 875.00 then
    raise exception 'FAIL 1f: subtotal is %, expected 875.00.', v_sub;
  end if;
  if v_gst <> 150.00 then
    raise exception 'FAIL 1g: gst_total is %, expected 150.00.', v_gst;
  end if;
  if v_total <> 1025.00 then
    raise exception 'FAIL 1h: total_amount is %, expected 1025.00.', v_total;
  end if;
  -- AKPC is intra-state: never IGST, so the pair must be exactly equal here.
  if v_cgst <> v_sgst then
    raise exception 'FAIL 1i: CGST (%) <> SGST (%) — AKPC should bill CGST+SGST only.', v_cgst, v_sgst;
  end if;

  -- CGST is the rounded half, SGST the residual, so the pair always sums back
  -- to gst_total even with an odd paise.
  if v_cgst + v_sgst <> v_gst then
    raise exception 'FAIL 1j: CGST (%) + SGST (%) <> gst_total (%).', v_cgst, v_sgst, v_gst;
  end if;

  perform set_config('smoke.direct_invoice', v_inv::text, true);

  raise notice 'PASS 1: direct invoice % created (2 items, 0 challans, total 1025.00)', v_number;
end $$;

-- ---------------------------------------------------------------------------
-- 2. A manual line must NOT be able to carry a source id (no fake links)
-- ---------------------------------------------------------------------------
do $$
declare
  v_failed boolean := false;
begin
  begin
    perform public.create_invoice(
      p_company_id  := current_setting('smoke.party')::uuid,
      p_invoice_date := date '2099-04-01',
      p_our    := '{}'::jsonb,
      p_party  := '{}'::jsonb,
      p_challans := '{}'::uuid[],
      p_lines := jsonb_build_array(
        jsonb_build_object(
          'line_no', 1,
          -- SMUGGLED SOURCE — must be rejected, not silently accepted
          'source_document_id', current_setting('smoke.challan')::uuid,
          'source_item_id', current_setting('smoke.item')::uuid,
          'line_type', 'other',
          'component_id', null,
          'item_name', 'Sneaky',
          'quantity', 1, 'unit', 'pieces',
          'unit_price', 1.00, 'gst_percent', 0
        )
      )
    );
  exception when others then
    v_failed := true;
  end;

  if not v_failed then
    raise exception 'FAIL 2: a direct invoice accepted a line with a source_document_id.';
  end if;

  raise notice 'PASS 2: direct invoice rejects a smuggled challan source';
end $$;

-- ---------------------------------------------------------------------------
-- 3. DIRECT INVOICE — edit: add, edit and remove a manual line
-- ---------------------------------------------------------------------------
do $$
declare
  v_inv uuid := current_setting('smoke.direct_invoice')::uuid;
  v_first_item uuid;
  v_count bigint;
  v_qty numeric;
  v_name text;
  v_hsn text;
  v_unit public.unit_type;
  v_total numeric;
  v_new uuid;
begin
  select id into v_first_item
  from public.invoice_items
  where invoice_id = v_inv and line_no = 1;

  -- (a) edit an existing manual line: every field, not just the rate
  perform public.update_invoice(
    p_invoice_id := v_inv,
    p_kept_lines := jsonb_build_array(
      jsonb_build_object(
        'id', v_first_item,
        'source_document_id', null,
        'quantity', 4,
        'unit_price', 250.00,
        'gst_percent', 18,
        'item_name', 'Manual Widget RENAMED',
        'hsn_code', '9999',
        'unit', 'set',
        'item_remarks', 'edited'
      )
    )
  );

  -- A direct line's editable set is quantity AND description (a manual line
  -- has no challan behind it holding them), so assert both moved.
  select quantity, item_name, hsn_code, unit
  into v_qty, v_name, v_hsn, v_unit
  from public.invoice_items where id = v_first_item;

  if v_qty <> 4 then
    raise exception 'FAIL 3a: direct-line quantity was not updated (is %).', v_qty;
  end if;
  if v_name <> 'Manual Widget RENAMED' then
    raise exception 'FAIL 3b: direct-line description was not updated (is %).', v_name;
  end if;
  if v_hsn <> '9999' then
    raise exception 'FAIL 3c: direct-line HSN was not updated (is %).', v_hsn;
  end if;
  if v_unit <> 'set' then
    raise exception 'FAIL 3d: direct-line unit was not updated (is %).', v_unit;
  end if;

  -- (b) add a manual line
  perform public.update_invoice(
    p_invoice_id := v_inv,
    p_add_lines := jsonb_build_array(
      jsonb_build_object(
        'line_no', 99,
        'source_document_id', null, 'source_item_id', null,
        'line_type', 'other', 'component_id', null,
        'item_name', 'Manual Gasket',
        'quantity', 5, 'unit', 'pieces',
        'unit_price', 20.00, 'gst_percent', 18
      )
    )
  );

  select count(*) into v_count
  from public.invoice_items where invoice_id = v_inv;
  if v_count <> 3 then
    raise exception 'FAIL 3e: expected 3 items after adding one, got %.', v_count;
  end if;

  -- (c) remove the line we just added
  select id into v_new
  from public.invoice_items
  where invoice_id = v_inv and item_name = 'Manual Gasket';

  perform public.update_invoice(
    p_invoice_id := v_inv,
    p_remove_line_ids := array[v_new]
  );

  select count(*) into v_count
  from public.invoice_items where invoice_id = v_inv;
  if v_count <> 2 then
    raise exception 'FAIL 3f: expected 2 items after removing one, got %.', v_count;
  end if;

  -- 4 x 250 = 1000 (+180) ; 10 x 12.50 = 125 (+15) => total 1320.00
  select total_amount into v_total from public.invoices where id = v_inv;
  if v_total <> 1320.00 then
    raise exception 'FAIL 3g: total after edit is %, expected 1320.00.', v_total;
  end if;

  raise notice 'PASS 3: direct invoice edit (edit fields, add line, remove line) works; total 1320.00';
end $$;

-- ---------------------------------------------------------------------------
-- 4. A direct invoice must refuse to gain a challan
-- ---------------------------------------------------------------------------
do $$
declare
  v_inv uuid := current_setting('smoke.direct_invoice')::uuid;
  v_failed boolean := false;
begin
  begin
    perform public.update_invoice(
      p_invoice_id := v_inv,
      p_add_challans := array[current_setting('smoke.challan')::uuid]
    );
  exception when others then
    v_failed := true;
  end;

  if not v_failed then
    raise exception 'FAIL 4: a direct invoice accepted an added challan — the modes are not exclusive.';
  end if;

  -- Still zero links after the rejected attempt.
  if exists (select 1 from public.invoice_challans where invoice_id = v_inv) then
    raise exception 'FAIL 4b: a challan link appeared on a direct invoice.';
  end if;

  raise notice 'PASS 4: direct invoice refuses a challan (modes stay exclusive)';
end $$;

-- ---------------------------------------------------------------------------
-- 5. A direct invoice must not be emptied (mode-aware post-condition)
-- ---------------------------------------------------------------------------
do $$
declare
  v_inv uuid := current_setting('smoke.direct_invoice')::uuid;
  v_ids uuid[];
  v_failed boolean := false;
begin
  select array_agg(id) into v_ids
  from public.invoice_items where invoice_id = v_inv;

  begin
    perform public.update_invoice(
      p_invoice_id := v_inv,
      p_remove_line_ids := v_ids
    );
  exception when others then
    v_failed := true;
  end;

  if not v_failed then
    raise exception 'FAIL 5: a direct invoice was allowed to lose its last item.';
  end if;

  raise notice 'PASS 5: direct invoice cannot be emptied';
end $$;

-- ---------------------------------------------------------------------------
-- 6. CHALLAN-BACKED INVOICE — unchanged behaviour (regression guard)
-- ---------------------------------------------------------------------------
do $$
declare
  v_party uuid := current_setting('smoke.party')::uuid;
  v_doc uuid := current_setting('smoke.challan')::uuid;
  v_item uuid := current_setting('smoke.item')::uuid;
  v_number text;
  v_inv uuid;
  v_type text;
  v_links bigint;
  v_sub numeric;
begin
  v_number := public.create_invoice(
    p_company_id  := v_party,
    p_invoice_date := date '2099-04-01',
    p_our    := jsonb_build_object('company_name', 'Smoke AKPC'),
    p_party  := jsonb_build_object('name', 'ZZ Smoke Test Party'),
    p_challans := array[v_doc],
    p_lines := jsonb_build_array(
      jsonb_build_object(
        'line_no', 1,
        'source_document_id', v_doc,
        'source_item_id', v_item,
        'line_type', 'component',
        'component_id', current_setting('smoke.component')::uuid,
        'item_name', 'ZZ Smoke Test Item',
        'quantity', 2, 'unit', 'pieces',
        'unit_price', 100.00, 'gst_percent', 18
      )
    )
  );

  select id, invoice_type into v_inv, v_type
  from public.invoices where invoice_number = v_number;

  if v_type <> 'challan' then
    raise exception 'FAIL 6a: a challan-backed invoice got invoice_type=''direct''.';
  end if;

  select count(*) into v_links from public.invoice_challans where invoice_id = v_inv;
  if v_links <> 1 then
    raise exception 'FAIL 6b: challan invoice has % links, expected 1.', v_links;
  end if;

  -- 2 x 100 = 200 (+36)
  select subtotal into v_sub from public.invoices where id = v_inv;
  if v_sub <> 200.00 then
    raise exception 'FAIL 6c: challan invoice subtotal is %, expected 200.00.', v_sub;
  end if;

  perform set_config('smoke.challan_invoice', v_inv::text, true);
  perform set_config('smoke.invoiced_challan', v_doc::text, true);

  raise notice 'PASS 6a: challan invoice % still gets invoice_type=''challan'' + 1 link', v_number;
end $$;

-- ---------------------------------------------------------------------------
-- 7. The old "one active invoice per challan" rule still holds
-- ---------------------------------------------------------------------------
do $$
declare
  v_failed boolean := false;
begin
  begin
    perform public.create_invoice(
      p_company_id  := current_setting('smoke.party')::uuid,
      p_invoice_date := date '2099-04-01',
      p_our    := '{}'::jsonb,
      p_party  := '{}'::jsonb,
      p_challans := array[current_setting('smoke.invoiced_challan')::uuid],
      p_lines := jsonb_build_array(
        jsonb_build_object(
          'line_no', 1,
          'source_document_id', current_setting('smoke.invoiced_challan')::uuid,
          'source_item_id', current_setting('smoke.item')::uuid,
          'line_type', 'other', 'component_id', null,
          'item_name', 'Double bill', 'quantity', 1, 'unit', 'pieces',
          'unit_price', 1.00, 'gst_percent', 0
        )
      )
    );
  exception when others then
    v_failed := true;
  end;

  if not v_failed then
    raise exception 'FAIL 7: the same challan was invoiced twice — the unique rule regressed.';
  end if;

  raise notice 'PASS 7: one-active-invoice-per-challan still enforced';
end $$;

-- ---------------------------------------------------------------------------
-- 8. A challan invoice keeps its rate-only edit semantics (regression guard)
--    update_invoice must IGNORE description / qty on a sourced line: those are
--    the challan's snapshot, not the user's to rewrite.
-- ---------------------------------------------------------------------------
do $$
declare
  v_inv uuid := current_setting('smoke.challan_invoice')::uuid;
  v_line uuid;
  v_qty numeric;
  v_name text;
begin
  select id into v_line
  from public.invoice_items where invoice_id = v_inv limit 1;

  perform public.update_invoice(
    p_invoice_id := v_inv,
    p_kept_lines := jsonb_build_array(
      jsonb_build_object(
        'id', v_line,
        'source_document_id', current_setting('smoke.invoiced_challan')::uuid,
        'quantity', 999,
        'unit_price', 150.00,
        'gst_percent', 18,
        'item_name', 'SHOULD NOT APPLY'
      )
    )
  );

  select quantity, item_name into v_qty, v_name
  from public.invoice_items where id = v_line;

  if v_qty <> 2 then
    raise exception 'FAIL 8a: a challan line''s quantity was rewritten to % (must stay the challan''s 2).', v_qty;
  end if;
  if v_name = 'SHOULD NOT APPLY' then
    raise exception 'FAIL 8b: a challan line''s description was rewritten.';
  end if;
  -- ...but the rate DID move: 2 x 150 = 300
  if (select total_amount from public.invoices where id = v_inv) <> 354.00 then
    raise exception 'FAIL 8c: challan rate edit did not recalculate (total is %, expected 354.00).',
      (select total_amount from public.invoices where id = v_inv);
  end if;

  raise notice 'PASS 8: challan lines stay rate/GST-only (qty + description unchanged)';
end $$;

-- ---------------------------------------------------------------------------
-- 9. A challan invoice must refuse to lose its last challan
-- ---------------------------------------------------------------------------
do $$
declare
  v_inv uuid := current_setting('smoke.challan_invoice')::uuid;
  v_failed boolean := false;
begin
  begin
    perform public.update_invoice(
      p_invoice_id := v_inv,
      p_remove_challans := array[current_setting('smoke.invoiced_challan')::uuid]
    );
  exception when others then
    v_failed := true;
  end;

  if not v_failed then
    raise exception 'FAIL 9: a challan invoice was allowed to lose its only challan.';
  end if;

  raise notice 'PASS 9: challan invoice still requires at least one challan';
end $$;

-- ---------------------------------------------------------------------------
-- 10. A challan invoice cannot use the direct-only per-line removal
-- ---------------------------------------------------------------------------
do $$
declare
  v_inv uuid := current_setting('smoke.challan_invoice')::uuid;
  v_line uuid;
  v_failed boolean := false;
begin
  select id into v_line from public.invoice_items where invoice_id = v_inv limit 1;

  begin
    perform public.update_invoice(
      p_invoice_id := v_inv,
      p_remove_line_ids := array[v_line]
    );
  exception when others then
    v_failed := true;
  end;

  if not v_failed then
    raise exception 'FAIL 10: a challan invoice accepted p_remove_line_ids.';
  end if;

  raise notice 'PASS 10: per-line removal is direct-only';
end $$;

-- ---------------------------------------------------------------------------
-- 11. Direct invoice delete cleans up completely
-- ---------------------------------------------------------------------------
do $$
declare
  v_inv uuid := current_setting('smoke.direct_invoice')::uuid;
begin
  perform public.delete_invoice(p_invoice_id := v_inv);

  if exists (select 1 from public.invoices where id = v_inv) then
    raise exception 'FAIL 11a: the invoice row survived delete.';
  end if;
  if exists (select 1 from public.invoice_items where invoice_id = v_inv) then
    raise exception 'FAIL 11b: invoice_items survived the delete.';
  end if;
  if exists (select 1 from public.invoice_challans where invoice_id = v_inv) then
    raise exception 'FAIL 11c: invoice_challans survived the delete.';
  end if;

  raise notice 'PASS 11: delete_invoice removes a direct invoice and its items cleanly';
end $$;

-- ---------------------------------------------------------------------------
-- 12. Backfill safety: an invoice_type default of ''challan'' never mislabels
-- ---------------------------------------------------------------------------
do $$
declare
  v_mismatched bigint;
begin
  -- Invariant: invoice_type='direct' <=> zero invoice_challans rows.
  -- If the mode column ever disagrees with the link table, the list/detail
  -- badge would lie, so assert the two agree in both directions.
  select count(*) into v_mismatched
  from public.invoices i
  where (i.invoice_type = 'direct')
     <> not exists (select 1 from public.invoice_challans ic where ic.invoice_id = i.id);

  if v_mismatched > 0 then
    raise exception 'FAIL 12: % invoice(s) have invoice_type disagreeing with their link count.', v_mismatched;
  end if;

  raise notice 'PASS 12: invoice_type and invoice_challans agree for every invoice';
end $$;

-- ---------------------------------------------------------------------------
-- Summary + cleanup
-- ---------------------------------------------------------------------------
do $$
begin
  raise notice '';
  raise notice '=== Direct Invoice smoke test: ALL CHECKS PASSED ===';
  raise notice 'Rolling back — no fixture data or invoice will persist.';
  raise notice '';
end $$;

rollback;